variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - linting

format:
  stage: linting
  image: ubuntu:22.04
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq
       python3-pip
    - pip3 install clang-format==14.0.0 cmake-format
  script:
    - ./scripts/run-format.sh

build-docker:
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq
       cmake
       g++
       likwid
       libpython3-dev
       python3-pybind11
  script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_POWERSENSOR2_PMT=ON -DBUILD_POWERSENSOR3_PMT=ON -DBUILD_PYTHON_PMT=ON
    - make install

test-das6:
  stage: test
  tags:
    - das6
  before_script:
    - module load spack/9.4.0
    - module load python/3.9.9
    - module load py-pybind11/2.10.1
    - module load cuda/11.6.2
  script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_POWERSENSOR2_PMT=ON -DBUILD_POWERSENSOR3_PMT=ON -DBUILD_NVML_PMT=ON -DBUILD_PYTHON_PMT=ON
    - make
    - $(pwd)/rapl/Rapl-test sleep 3
    - $(pwd)/nvml/NVML-test sleep 3
    - PYTHONPATH=$PYTHONPATH:$(pwd)/python python3 ${CI_PROJECT_DIR}/python/PythonNVMLDemo.py
